# Generated by Django 3.0.5 on 2021-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='first',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='third',
            field=models.IntegerField(default=0),
        ),
    ]
