# Generated by Django 3.0.5 on 2021-06-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20210613_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='grey', max_length=32, unique=True),
        ),
    ]
