# Generated by Django 3.0.5 on 2021-06-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20210613_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
    ]
