# Generated by Django 3.0.5 on 2021-06-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_remove_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='white', max_length=32),
        ),
    ]
